# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: LocalStack
  - init: pip install localstack
  - command: localstack start
      
  - name: AWS CLI and SAM
  - init: >
      pip install aws-sam-cli &&
      pip install aws-sam-cli-local &&
      pip install awscli &&
      pip install awscli-local

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
