# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: LocalStack init & start
  - init: >
      echo 'init LocalStack install' &&
      pip install localstack
  - command: localstack start
      
  - name: AWS CLI & SAM install
  - init: >
      echo 'init AWS SAM install' &&
      pip install aws-sam-cli &&
      pip install aws-sam-cli-local &&
      echo 'init AWS CLI install' &&
      pip install awscli &&
      pip install awscli-local

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
