# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: AWS CLI & SAM install
  - init: >
      echo 'init AWS SAM install' &&
      pip install aws-sam-cli &&
      echo 'init AWS CLI install' &&
      pip install awscli

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
